// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr5b-6fCOfAcNwes1yHxmA1TrGroN3WHM',
    appId: '1:406229984092:web:54d6a4f16e6c59aa809799',
    messagingSenderId: '406229984092',
    projectId: 'flutterfire-configure-66011',
    authDomain: 'flutterfire-configure-66011.firebaseapp.com',
    storageBucket: 'flutterfire-configure-66011.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFJFtCvhMXAUWUiZMYoXs9A6HvTJxKFs',
    appId: '1:406229984092:android:d68857d9e9563227809799',
    messagingSenderId: '406229984092',
    projectId: 'flutterfire-configure-66011',
    storageBucket: 'flutterfire-configure-66011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtbdJUaPGJ287yMXUcPiS7lp-y8MkOnHQ',
    appId: '1:406229984092:ios:e01504bf0b510da0809799',
    messagingSenderId: '406229984092',
    projectId: 'flutterfire-configure-66011',
    storageBucket: 'flutterfire-configure-66011.firebasestorage.app',
    iosBundleId: 'com.example.flutterOfflineQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtbdJUaPGJ287yMXUcPiS7lp-y8MkOnHQ',
    appId: '1:406229984092:ios:e01504bf0b510da0809799',
    messagingSenderId: '406229984092',
    projectId: 'flutterfire-configure-66011',
    storageBucket: 'flutterfire-configure-66011.firebasestorage.app',
    iosBundleId: 'com.example.flutterOfflineQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr5b-6fCOfAcNwes1yHxmA1TrGroN3WHM',
    appId: '1:406229984092:web:d0cb2765c0906d6f809799',
    messagingSenderId: '406229984092',
    projectId: 'flutterfire-configure-66011',
    authDomain: 'flutterfire-configure-66011.firebaseapp.com',
    storageBucket: 'flutterfire-configure-66011.firebasestorage.app',
  );
}
